# Generated by Django 3.0.5 on 2020-12-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200922_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='Gaming', max_length=255),
        ),
    ]
