# Generated by Django 3.1.4 on 2020-12-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
